name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Angular app for GitHub Pages
        run: npm run build -- --configuration production --base-href="/deployment-project/" --output-path=dist
      
      - name: Debug build output
        run: |
          echo "Build completed. Directory structure:"
          find dist -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -10
          echo "Checking index.html content:"
          if [ -f "dist/index.html" ]; then
            head -10 dist/index.html
          else
            echo "index.html not found in dist/"
          fi
      
      - name: Create 404.html
        run: |
          if [ -f "dist/index.html" ]; then
            cp dist/index.html dist/404.html
          else
            echo "Error: index.html not found"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
