name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Angular app for GitHub Pages
        run: npm run build -- --configuration production --base-href="/deployment-project/"
      
      - name: Debug and prepare files
        run: |
          echo "=== Build Output Structure ==="
          find dist -type f | head -20
          
          echo -e "\n=== Looking for index.html ==="
          find dist -name "index.html" -type f
          
          # Create a clean deploy directory
          mkdir -p deploy
          
          # Copy files from the correct location
          if [ -d "dist/deployment-project/browser" ]; then
            echo "Using browser output (Angular 17+)"
            cp -r dist/deployment-project/browser/* deploy/
            SOURCE_DIR="browser"
          elif [ -d "dist/deployment-project" ]; then
            echo "Using deployment-project output"
            cp -r dist/deployment-project/* deploy/
            SOURCE_DIR="deployment-project"
          else
            echo "ERROR: Cannot find built files"
            exit 1
          fi
          
          echo -e "\n=== Deploy directory contents ==="
          ls -la deploy/
          
          # Verify index.html exists in deploy directory
          if [ -f "deploy/index.html" ]; then
            echo "✓ index.html found in deploy directory"
            echo "Creating 404.html..."
            cp deploy/index.html deploy/404.html
            echo "✓ 404.html created"
          else
            echo "ERROR: index.html not found in deploy directory"
            exit 1
          fi
          
          echo -e "\n=== Final deploy directory ==="
          ls -la deploy/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
